version: '3.6'
services:
  grafana: 
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - /IOTServer/grafana:/etc/grafana:rw
      - /IOTServer/grafana:/var/lib/grafana:rw
    restart: on-failure
    depends_on:
      - influxdb

  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    ports:
      - 8086:8086
    volumes:
      - /IOTServer/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /IOTServer/influxdb:/var/lib/influxdb
    #network_mode: "host"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8086/ping"]
      interval: 60s
      timeout: 1s
      retries: 10

  telegraf:
    container_name: telegraf
    image: arm32v7/telegraf
    volumes:
      - /IOTServer/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro 
      - /opt:/opt:ro     
    depends_on:
      - influxdb
      
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    user: "1001:1001"
    ports:
      - 1883:1883
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /IOTServer/mqtt:/mosquitto/config:ro
      - /IOTServer/mqtt:/mosquitto/data:rw
      - /IOTServer/log:/mosquitto/log:rw
    restart: on-failure

  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /IOTServer/portainer:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

  nginx:
    container_name: nginx
    image: arm32v7/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /IOTServer/nginx:/etc/nginx:rw
      - /IOTServer/log:/config/log/nginx
      - /IOTServer/nginx/www:/opt/www
      - /etc/letsencrypt:/etc/letsencrypt:ro
    #network_mode: "host"

  kmlserver:
    container_name: kmlserver
    image: churruscat/kmlserver
    ports:
      - 5000:5000
    volumes:
      - /IOTServer/kmlserver:/kmlserver:rw
      - /IOTServer/kmlserver/log:/kmlserver/log:rw
    restart: on-failure

  mqttdbs:
    container_name: mqttdbs
    image: churruscat/mqttdbs:latest
    volumes:
      - /IOTServer/mqttdbs:/etc/mqttdbs:rw
    depends_on:
      - mosquitto
      - influxdb
    restart: on-failure


